import CartContextProvider from "@/context/cartContext";
import "./globals.css";

export const metadata = {
  title: "Al Hikmah Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>{children}</CartContextProvider>
      </body>
    </html>
  );
}
